In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from keras.utils import np_utils
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, Dense, Flatten
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import load_model
from PIL import Image, ImageOps

In [5]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [3]:
print(X_train.shape)
print(X_test.shape)

(60000, 28, 28)
(10000, 28, 28)


In [6]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [7]:
y_train[0]

5

In [8]:
X_train = X_train.reshape(60000, 28, 28, 1).astype('float32')
X_test = X_test.reshape(10000, 28, 28, 1).astype('float32')

In [9]:
number_of_classes = 10
Y_train = np_utils.to_categorical(y_train, number_of_classes)
Y_test = np_utils.to_categorical(y_test, number_of_classes)

In [10]:
Y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [11]:
model = Sequential()
model.add(Conv2D(64, (3, 3), input_shape=(28, 28, 1), activation="relu"))
model.add(Conv2D(32, (3, 3), activation="relu"))
model.add(Flatten())
model.add(Dense(number_of_classes, activation="softmax"))

In [12]:
model.compile(loss='categorical_crossentropy', optimizer="Adam", metrics=["accuracy"])

In [13]:
model.fit(X_train, Y_train, batch_size=32, epochs=5, validation_data=(X_test,Y_test))

Epoch 1/5
1875/1875 [==============================] - 110s 58ms/step - loss: 0.2560 - accuracy: 0.9498 - val_loss: 0.1130 - val_accuracy: 0.9649
Epoch 2/5
1875/1875 [==============================] - 107s 57ms/step - loss: 0.0736 - accuracy: 0.9776 - val_loss: 0.0736 - val_accuracy: 0.9774
Epoch 3/5
1875/1875 [==============================] - 108s 58ms/step - loss: 0.0509 - accuracy: 0.9844 - val_loss: 0.0820 - val_accuracy: 0.9768
Epoch 4/5
1875/1875 [==============================] - 107s 57ms/step - loss: 0.0369 - accuracy: 0.9886 - val_loss: 0.0831 - val_accuracy: 0.9764
Epoch 5/5
1875/1875 [==============================] - 108s 57ms/step - loss: 0.0310 - accuracy: 0.9901 - val_loss: 0.0938 - val_accuracy: 0.9795


In [14]:
metrics = model.evaluate(X_test, Y_test, verbose=0)
print("Metrics (Test Loss & Test Accuracy): ")
print(metrics)

Metrics (Test Loss & Test Accuracy): 
[0.09375874698162079, 0.9794999957084656]


In [15]:
prediction = model.predict(X_test[:4])
print(prediction)

1/1 [==============================] - 0s 59ms/step
[[1.8793485e-09 4.9245682e-14 4.9641802e-09 2.1709742e-07 2.2575254e-16
  2.4648419e-12 1.0347111e-15 9.9999976e-01 6.2261800e-09 1.5220307e-08]
 [1.5467502e-10 1.1888469e-10 9.9999821e-01 1.5549831e-09 1.8143878e-13
  1.6657411e-17 1.8094195e-06 6.0171255e-14 1.9857504e-08 9.8634267e-19]
 [2.2136755e-05 9.9782419e-01 2.5154624e-04 4.3189460e-10 1.8729313e-03
  1.2610208e-05 3.1522212e-08 1.9331114e-06 1.4651580e-05 4.5958548e-10]
 [1.0000000e+00 4.5233477e-19 1.9306085e-11 2.3757972e-16 1.2082986e-14
  9.8858252e-14 6.2978490e-11 4.9105095e-14 5.5239924e-11 1.1674123e-10]]


In [17]:
print(np.argmax(prediction, axis=1))
print(Y_test[:4])

[7 2 1 0]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [18]:
model.save("model.h5")

In [19]:
model=load_model("model.h5")

In [ ]:
img = Image.open("sample.png").convert("L")
img = img.resize((28, 28))
img2arr = np.array(img)
img2arr = img2arr.reshape(1, 28, 28, 1)
results  = model.predict(img2arr)
results = np.argmax(results,axis = 1)
results = pd.Series(results,name="Label")
print(results)