In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from keras.utils import np_utils
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, Dense, Flatten
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import load_model
from PIL import Image, ImageOps
import numpy

In [2]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [3]:
print(X_train.shape)
print(X_test.shape)

(60000, 28, 28)
(10000, 28, 28)


In [4]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [5]:
y_train[0]

5

In [6]:
X_train = X_train.reshape(60000, 28, 28, 1).astype('float32')
X_test = X_test.reshape(10000, 28, 28, 1).astype('float32')

In [7]:
number_of_classes = 10
Y_train = np_utils.to_categorical(y_train, number_of_classes)
Y_test = np_utils.to_categorical(y_test, number_of_classes)

In [8]:
Y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [9]:
model = Sequential()
model.add(Conv2D(64, (3, 3), input_shape=(28, 28, 1), activation="relu"))
model.add(Conv2D(32, (3, 3), activation="relu"))
model.add(Flatten())
model.add(Dense(number_of_classes, activation="softmax"))

In [10]:
model.compile(loss='categorical_crossentropy', optimizer="Adam", metrics=["accuracy"])

In [11]:
model.fit(X_train, Y_train, batch_size=32, epochs=5, validation_data=(X_test,Y_test))

Epoch 1/5
1875/1875 [==============================] - 213s 113ms/step - loss: 0.2033 - accuracy: 0.9540 - val_loss: 0.0817 - val_accuracy: 0.9735
Epoch 2/5
1875/1875 [==============================] - 213s 113ms/step - loss: 0.0633 - accuracy: 0.9805 - val_loss: 0.0798 - val_accuracy: 0.9741
Epoch 3/5
1875/1875 [==============================] - 208s 111ms/step - loss: 0.0456 - accuracy: 0.9859 - val_loss: 0.0714 - val_accuracy: 0.9788
Epoch 4/5
1875/1875 [==============================] - 200s 107ms/step - loss: 0.0328 - accuracy: 0.9901 - val_loss: 0.1033 - val_accuracy: 0.9751
Epoch 5/5
1875/1875 [==============================] - 196s 105ms/step - loss: 0.0301 - accuracy: 0.9908 - val_loss: 0.0887 - val_accuracy: 0.9794


In [12]:
metrics = model.evaluate(X_test, Y_test, verbose=0)
print("Metrics (Test Loss & Test Accuracy): ")
print(metrics)

Metrics (Test Loss & Test Accuracy): 
[0.0887439101934433, 0.9793999791145325]


In [13]:
prediction = model.predict(X_test[:4])
print(prediction)

1/1 [==============================] - 0s 99ms/step
[[2.57000757e-11 7.57546739e-20 2.50762952e-12 4.73237582e-09
  2.79903940e-18 1.57761911e-16 1.68294923e-19 1.00000000e+00
  3.91002978e-14 3.72969044e-13]
 [2.38580267e-11 2.35477761e-13 1.00000000e+00 1.26212246e-13
  3.97029880e-15 8.70535527e-19 1.76470193e-11 3.84722789e-19
  1.66029723e-14 1.38530928e-16]
 [5.76447744e-11 9.99969125e-01 1.98586321e-08 7.94167579e-11
  3.84283849e-09 3.25735861e-09 2.48177265e-08 1.73277777e-12
  3.09191564e-05 4.02236404e-12]
 [9.99991059e-01 2.88438192e-13 1.91632932e-09 1.70229109e-12
  1.09673685e-11 5.95869057e-13 8.99515635e-06 8.39147675e-12
  2.47417842e-09 5.09295894e-09]]


In [14]:
print(numpy.argmax(prediction, axis=1))
print(Y_test[:4])

[7 2 1 0]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [15]:
model.save("model.h5")

In [16]:
model=load_model("model.h5")